"""initial migration

Revision ID: 32758341a3bd
Revises: 
Create Date: 2026-05-04 21:52:27.639186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32758341a3bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conducteurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('numero_permis', sa.String(length=50), nullable=False),
    sa.Column('date_expiration_permis', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_permis')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'gestionnaire', 'conducteur'), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('type_carburant', sa.Enum('essence', 'diesel', 'hybride', 'electrique'), nullable=False),
    sa.Column('km_initial', sa.Float(), nullable=True),
    sa.Column('km_actuel', sa.Float(), nullable=True),
    sa.Column('statut', sa.Enum('actif', 'maintenance', 'hors_service'), nullable=True),
    sa.Column('categorie', sa.Enum('leger', 'utilitaire', 'poids_lourd'), nullable=True),
    sa.Column('couleur', sa.String(length=50), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_table('affectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('conducteur_id', sa.Integer(), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('type_affectation', sa.Enum('permanente', 'temporaire'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conducteur_id'], ['conducteurs.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('type_alerte', sa.Enum('sur_consommation', 'entretien', 'permis_expire', 'autre'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('seuil_valeur', sa.Float(), nullable=True),
    sa.Column('valeur_actuelle', sa.Float(), nullable=True),
    sa.Column('lue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pleins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('date_plein', sa.DateTime(), nullable=False),
    sa.Column('km_compteur', sa.Float(), nullable=False),
    sa.Column('litres', sa.Float(), nullable=False),
    sa.Column('prix_litre', sa.Float(), nullable=False),
    sa.Column('cout_total', sa.Float(), nullable=False),
    sa.Column('station', sa.String(length=150), nullable=True),
    sa.Column('type_carburant', sa.String(length=50), nullable=True),
    sa.Column('plein_complet', sa.Boolean(), nullable=True),
    sa.Column('consommation_100km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pleins')
    op.drop_table('alertes')
    op.drop_table('affectations')
    op.drop_table('vehicules')
    op.drop_table('utilisateurs')
    op.drop_table('conducteurs')
    # ### end Alembic commands ###
