Listen 443

SSLSessionCache shmcb:/usr/local/apache2/logs/ssl_scache(512000)
SSLSessionCacheTimeout 300

<VirtualHost *:80>
    ServerName parc-auto.lacipres.org
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName parc-auto.lacipres.org

    SSLEngine on
    SSLCertificateFile    /etc/ssl/parc-auto/parc-auto.crt
    SSLCertificateKeyFile /etc/ssl/parc-auto/parc-auto.key

    DocumentRoot /usr/local/apache2/htdocs

    ProxyPreserveHost On
    ProxyPass /api http://backend:5000/api
    ProxyPassReverse /api http://backend:5000/api

    <Directory /usr/local/apache2/htdocs>
        Options -MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
