# Redirect HTTP to HTTPS
<VirtualHost *:80>
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

# HTTPS Virtual Host
<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile    /etc/ssl/parc-auto/parc-auto.crt
    SSLCertificateKeyFile /etc/ssl/parc-auto/parc-auto.key

    DocumentRoot /usr/local/apache2/htdocs

    ProxyPass /api http://backend:5000/api
    ProxyPassReverse /api http://backend:5000/api

    <Directory /usr/local/apache2/htdocs>
        Options -MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
